project_id = "ismtjnkzgfsrcstlyops"

[functions.send-connection-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.reset-password-otp]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = false

[functions.send-push-notification]
enabled = true
verify_jwt = false
import_map = "./functions/send-push-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-push-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-push-notification/*.html" ]
